
server:
    port: 7777

db:
    type: "postgres"
    port: 5433
    username: "postgres"
    host:     "localhost"
    database: "navkar_my_tap"
    password: "Oneclick1@"
    synchronize: true


    
jwt:
    ExpireIn: 2592000
    SecretKey: "mySecre@tKey"

# email:
#     host: "smtpout.secureserver.net"
#     user: "no-reply@shoploba.com"
#     pass: "3!hg2022"
#     port: 465
#     secure: true

otp:
    enabled: true
    expireTime: 10

others:
    host: "http://localhost:4200/"

socialLinks:
    facebook: ""
    instagram: ""
    linkedin: ""
    twitter: ""
    youtube: ""
    

